### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Lehersun** [retailcrm/api-client-php#109]
Hello. I've tried to install api-client-php via "composer require retailcrm/api-client-php:"~6.0"" and got the error:   
Problem 1
    - retailcrm/api-client-php[v6.0.0, ..., v6.0.4] require liip/serializer ^2.0 -> satisfiable by liip/serializer[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - liip/serializer[2.0.0, ..., 2.0.3] require php ^7.2 -> your php version (8.0.9) does not satisfy that requirement.
    - Root composer.json requires retailcrm/api-client-php ~6.0 -> satisfiable by retailcrm/api-client-php[v6.0.0, ..., v6.0.4].
Same time if i try to use PHP v.7.2 i get issue with require"php": ">=7.3.0".

**Comment by Neur0toxine** [comment]
Hello!

The API client is dependent on the `liip/serializer` library. Although the API client itself supports PHP 8, the `liip/serializer` does not support it. That's why you're getting an error while trying to install the client.

We're working on this issue. For now you can use PHP 7.3 or 7.4. PHP 7.2 is not supported because it hit EOL in the previous year.

**Comment by warendmir** [comment]
Hi, i have same problem too! Just try to use `--ignore-platform-reqs` at the end of `composer require...` line
And wait for php8 update)
